
server {
    listen 80;
    server_name localhost;

    location / {
        include uwsgi_params;
        uwsgi_pass filmoteca-flask;
    }
}

server {
    listen 81;
    server_name localhost;

    location / {
        include uwsgi_params;
        uwsgi_pass filmoteca-flask2;
    }
}
