name: Deploy on Merge to Main

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:  # Permite ejecución manual desde la interfaz

jobs:
  deploy:
    runs-on: [gitea-runner-1, docker]
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Force-sync repository
        run: |
          cd /data/filmoteca
          git fetch origin
          git checkout main
          git reset --hard origin/main
          git clean -fd

      - name: Unzip images
        run: |
          7z x /data/pack_images.7z -o/data/filmoteca/www -y
          echo "Images extracted successfully"

      - name: Restart container
        run: |
          docker restart filmoteca-flask
          echo "Container restarted successfully"
