name: Deploy Filmoteca to production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: gitea-runner-1
    steps:
      - name: Pull latest changes
        run: |
          cd /data/filmoteca
          echo "git pull origin main"
          ls

      - name: Unzip images
        run: |
          echo "7z x /var/wwww/web-flask/data/pack_images.7z -o/data/filmoteca/www"

      - name: Run deployment script
        run: |
          echo "bash /webserver/run.sh"
