services:
  flask:
    image: filmoteca-flask:latest
    container_name: filmoteca-flask
    restart: unless-stopped
    volumes:
      - "/home/user/docker-app/webserver/filmoteca/filmoteca:/usr/src/app/filmoteca"
      - "/home/user/docker-app/webserver/filmoteca/docker/wsgi.ini:/usr/src/app/filmoteca/wsgi.ini"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
#      - "/mnt/hgfs/films:/mnt/hgfs/movies:ro"
#      - "/mnt/hgfs/ext_films:/mnt/hgfs/ext_movies:ro"
    environment:
      - FLASK_ENV=production
    command: sh -c "uwsgi --ini /usr/src/app/filmoteca/wsgi.ini"
    networks:
      - netflask

  flask2:
    image: filmoteca-flask:latest
    container_name: filmoteca-flask2
    restart: unless-stopped
    volumes:
      - "/home/user/docker-app/webserver/filmoteca/filmoteca:/usr/src/app/filmoteca2"
      - "/home/user/docker-app/webserver/filmoteca/docker/wsgi2.ini:/usr/src/app/filmoteca2/wsgi.ini"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
#      - "/mnt/hgfs/films:/mnt/hgfs/movies:ro"
#      - "/mnt/hgfs/ext_films:/mnt/hgfs/ext_movies:ro"
    environment:
      - FLASK_ENV=development
    command: sh -c "uwsgi --ini /usr/src/app/filmoteca2/wsgi.ini"
    networks:
      - netflask

  nginx:
    image: nginx:latest
    container_name: nginx-flask
    restart: unless-stopped
    volumes:
      - "/home/user/docker-app/webserver/filmoteca/docker/nginx.conf:/etc/nginx/nginx.conf"
#      - "/home/user/docker-app/webserver/filmoteca/docker/default.conf:/etc/nginx/conf.d/default.conf"
      - "/var/log/nginx-flask:/var/log/nginx"
#      - "/home/user/docker-app/webserver/filmoteca/docker/sites.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
#    command: sh -c "rm /etc/nginx/conf.d/default.conf"
    ports:
      - 8080:80
      - 8084:81
    depends_on:
      - flask
      - flask2
    networks:
      - netflask

networks:
  netflask:
