user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    gzip on;

    upstream filmoteca-flask {
        server flask:8080;  # Flask en el contenedor `flask`
    }

    upstream filmoteca-flask2 {
        server flask2:3030;  # Flask en el contenedor `flask2`
    }

	server {
    	listen 80;
    	server_name localhost;

		location ~* ^/uwsgi {
			deny all;
		}

	    location / {
    	    include uwsgi_params;
       		uwsgi_pass filmoteca-flask;
    	}
	}

	server {
    	listen 81;
	    server_name localhost;

		location ~* ^/uwsgi {
			deny all;
		}

    	location / {
        	include uwsgi_params;
	        uwsgi_pass filmoteca-flask2;
    	}
	}
}
