access_log /var/log/nginx/access.log;
error_log /var/log/nginx/error.log;

upstream filmoteca-flask {
  server filmoteca-flask:8080;
}

server {
	listen 80;
	server_name localhost;

	location / {
		include uwsgi_params;
		uwsgi_pass filmoteca-flask;
	}
}

upstream filmoteca-flask2 {
  server filmoteca-flask:3030;
}

server {
	listen 81;
	server_name localhost;

	location / {
		include uwsgi_params;
		uwsgi_pass filmoteca-flask2;
	}
}
