[uwsgi]
chdir = /usr/src/app/filmoteca
wsgi-file = /usr/src/app/filmoteca/server.py
callable = application
socket = 0.0.0.0:8080
#enable-threads = true
processes = 1
#workers = 1
#threads = 2
master = true
chmod-socket = 660
vacuum = true
die-on-term = true
#logto = /var/log/nginx/%n.log
#uid = 1000
#gid = 1000
#idle = 300
# lazy-apps = true
#max-requests = 100
#limit-as = 256
#buffer-size = 32768
#harakiri = 60         # Mata workers que excedan 60 segundos
#reload-on-rss = 256
