x-healthchecks:
  interval: 30s
  timeout: 10s
  retries: 3
  nginx: &nginx-healthcheck
    test: ["CMD", "nginx", "-t"]
  gateway: &gateway-healthcheck
    test: ["CMD", "curl", "-f", "http://localhost:3000/gateway/health"]
  database: &database-healthcheck
    test: ["CMD", "curl", "-f", "http://localhost:3003/database/health"]
  auth: &auth-healthcheck
    test: ["CMD", "curl", "-f", "http://localhost:3001/auth/health"]
  i18n: &i18n-healthcheck
    test: ["CMD", "curl", "-f", "http://localhost:3002/i18n/health"]
  app: &app-healthcheck
    test: ["CMD", "curl", "-f", "http://localhost:5000/health"]


services:

  web-base:
    image: filmoteca-web-base:latest
    container_name: filmoteca-web-base
    build:
      context: ${PWD}
      dockerfile: infra/containers/web/base/Dockerfile
      network: host
    networks: [filmoteca-net]

  database:
    image: filmoteca-database
    container_name: filmoteca-database
    build:
      context: ${PWD}
      dockerfile: infra/containers/web/database/Dockerfile
      network: host
    env_file: .env
    volumes:
      - database:/app/web/database
      - shared:/app/web/shared:ro
      - data:/app/data
    networks: [filmoteca-net]
    healthcheck: *database-healthcheck
    restart: always

  auth:
    image: filmoteca-auth
    container_name: filmoteca-auth
    build:
      context: ${PWD}
      dockerfile: infra/containers/web/auth/Dockerfile
      network: host
    env_file: .env
    volumes:
      - auth:/app/web/auth
      - shared:/app/web/shared:ro
    depends_on:
      database:
        condition: service_healthy
    networks: [filmoteca-net]
    healthcheck: *auth-healthcheck
    restart: always

  i18n:
    image: filmoteca-i18n
    container_name: filmoteca-i18n
    build:
      context: ${PWD}
      dockerfile: infra/containers/web/i18n/Dockerfile
      network: host
    env_file: .env
    volumes:
      - i18n:/app/web/i18n
      - shared:/app/web/shared:ro
    networks: [filmoteca-net]
    healthcheck: *i18n-healthcheck
    restart: always

  gateway:
    image: filmoteca-gateway
    container_name: filmoteca-gateway
    build:
      context: ${PWD}
      dockerfile: infra/containers/web/gateway/Dockerfile
      network: host
    env_file: .env
    volumes:
      - gateway:/app/web/gateway
      - shared:/app/web/shared:ro
      - frontend:/app/web/frontend/public:ro
      - data:/app/data:ro
    depends_on:
      database:
        condition: service_healthy
      auth:
        condition: service_healthy
      i18n:
        condition: service_healthy
    networks: [filmoteca-net]
    healthcheck: *gateway-healthcheck
    restart: always

  nginx:
    image: filmoteca-nginx
    container_name: filmoteca-nginx
    build:
      context: ${PWD}
      dockerfile: infra/containers/web/nginx/Dockerfile
      network: host
    ports:
      - "8080:443"
    volumes:
      - ../../data/logs/nginx:/var/log/nginx
    depends_on:
      gateway:
        condition: service_healthy
    networks: [filmoteca-net]
    healthcheck: *nginx-healthcheck
    restart: always

  app:
    image: filmoteca-app
    container_name: filmoteca-app
    build:
      context: ${PWD}
      dockerfile: infra/containers/app/Dockerfile
      network: host
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    dns: [1.1.1.1, 8.8.8.8]
    ports: ["5000:5000"]
    volumes:
      - app:/usr/src/app/app
      - data:/usr/src/app/data
    networks: [filmoteca-net]
    healthcheck: *app-healthcheck
    restart: always

networks:
  filmoteca-net:
    name: filmoteca-net
    driver: bridge
    enable_ipv6: false

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../../web/database

  auth:
    name: auth
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../../web/auth

  i18n:
    name: i18n
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../../web/i18n

  gateway:
    name: gateway
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../../web/gateway

  shared:
    name: shared
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../../web/shared

  frontend:
    name: frontend
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../../web/frontend/public

  data:
    name: data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../../data

  app:
    name: app
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../../app
